#!/usr/bin/env bash
set -euo pipefail

RUN_ID=${RUN_ID:-split_2to8_dim256l6_bs524k_tp4}
DATA_PATH=${DATA_PATH:-./data/datasets/fineweb10B_sp1024}
TOKENIZER_PATH=${TOKENIZER_PATH:-./data/tokenizers/fineweb_1024_bpe.model}

CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES:-0,1,2,3} \
DATA_PATH="$DATA_PATH" \
TOKENIZER_PATH="$TOKENIZER_PATH" \
RUN_ID="$RUN_ID" \
TRAIN_BATCH_TOKENS=${TRAIN_BATCH_TOKENS:-524288} \
TRAIN_SEQ_LEN=${TRAIN_SEQ_LEN:-1024} \
VAL_BATCH_SIZE=${VAL_BATCH_SIZE:-524288} \
VAL_LOSS_EVERY=0 \
VAL_LOSS_EVERY_TOKENS=20000000 \
VAL_DOWNSTREAM_EVERY=0 \
VAL_DOWNSTREAM_EVERY_TOKENS=100000000 \
DOWNSTREAM_DATA_PATH=${DOWNSTREAM_DATA_PATH:-./data/downstream} \
DOWNSTREAM_MAX_EXAMPLES=${DOWNSTREAM_MAX_EXAMPLES:-32} \
DOWNSTREAM_FEWSHOT=${DOWNSTREAM_FEWSHOT:-5} \
ITERATIONS=${ITERATIONS:-999999999} \
MAX_WALLCLOCK_SECONDS=${MAX_WALLCLOCK_SECONDS:-0} \
NUM_LAYERS=6 \
MODEL_DIM=512 \
NUM_ARTERIES=2 \
NUM_HEADS=${NUM_HEADS:-2} \
NUM_KV_HEADS=${NUM_KV_HEADS:-2} \
MLP_MULT=${MLP_MULT:-2} \
ATTN_WINDOWS=${ATTN_WINDOWS:-1024,4096} \
XSA_ARTERIES=${XSA_ARTERIES:-} \
MIXER_DIM=${MIXER_DIM:-128} \
MIXER_HEADS=${MIXER_HEADS:-2} \
MIXER_EVERY=1 \
MIXER_START_LAYER=0 \
ARTERY_SPLIT_TOKEN_MILESTONES=2000000000,4000000000 \
FINAL_TRAIN_TOKENS=8000000000 \
SPLIT_WARMDOWN_FRACTION=0.25 \
SPLIT_WARMUP_FRACTION=0.05 \
SPLIT_CHECKPOINT_DIR=${SPLIT_CHECKPOINT_DIR:-split_checkpoints/${RUN_ID}} \
TORCH_COMPILE=${TORCH_COMPILE:-1} \
GRAD_CHECKPOINT_LAYERS=${GRAD_CHECKPOINT_LAYERS:-1} \
WARMUP_STEPS=${WARMUP_STEPS:-20} \
SPLIT_WARMUP_STEPS=${SPLIT_WARMUP_STEPS:-20} \
WANDB_PROJECT=${WANDB_PROJECT:-parameter-golf-arterial-mixer} \
WANDB_MODE=${WANDB_MODE:-online} \
torchrun --standalone --nproc_per_node=4 train_gpt_arterial_mixer.py
