#!/usr/bin/env bash
set -euo pipefail

RUN_ID=${RUN_ID:-latprof_grouped_10l_a384x2_mix192_h3_w1024_4096_pure_ctx16k_bs524k}

ARTERY_GROUPED_LAYOUT=1 \
PROFILE_LATENCY=1 \
PROFILE_LATENCY_STEPS=${PROFILE_LATENCY_STEPS:-30} \
RUN_ID="$RUN_ID" \
VOCAB_SIZE=${VOCAB_SIZE:-1024} \
DATA_PATH=${DATA_PATH:-./data/datasets/fineweb10B_sp1024} \
TOKENIZER_PATH=${TOKENIZER_PATH:-./data/tokenizers/fineweb_1024_bpe.model} \
TRAIN_BATCH_TOKENS=${TRAIN_BATCH_TOKENS:-524288} \
TRAIN_SEQ_LEN=${TRAIN_SEQ_LEN:-16384} \
VAL_LOSS_EVERY=0 \
TRAIN_LOG_EVERY=1 \
WARMUP_STEPS=${WARMUP_STEPS:-10} \
TORCH_COMPILE=0 \
NUM_LAYERS=10 \
MODEL_DIM=768 \
NUM_ARTERIES=2 \
NUM_HEADS=3 \
NUM_KV_HEADS=3 \
MLP_MULT=2 \
ATTN_WINDOWS=1024,4096 \
XSA_ARTERIES= \
MIXER_DIM=192 \
MIXER_HEADS=3 \
MIXER_EVERY=1 \
MIXER_START_LAYER=0 \
MIXER_UNET_RESIDUAL_KV=0 \
MIXER_UNET_RESIDUAL_XSA_ONLY=0 \
MIXER_SLOT_ROPE=0 \
python3 train_gpt_arterial_mixer.py
